apiVersion: v1
kind: Service
metadata:
  name: {{ default .Chart.Name .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
  labels:
    app: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
